name: PHP Quality Assurance

on:
    push:
    pull_request:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:

    static-qa:
        runs-on: ubuntu-latest
        if: ${{ !contains(github.event.head_commit.message, 'skip qa') }}

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none
                    tools: cs2pr

            -   name: Install dependencies
                uses: ramsey/composer-install@v2

            -   name: Check code styles
                run: ./vendor/bin/phpcs -q ${{ ((github.event_name == 'pull_request') && '--report-checkstyle="phpcs-report.xml" ') || '' }}--report-full --runtime-set ignore_errors_on_exit 1 --runtime-set ignore_warnings_on_exit 1

            -   name: Annotate code styles for PRs
                if: ${{ github.event_name == 'pull_request' }}
                run: cs2pr --graceful-warnings phpcs-report.xml

            -   name: Check Psalm
                run: ./vendor/bin/psalm ${{ ((github.event_name == 'pull_request') && '--output-format=github ') || '' }} --no-suggestions --find-unused-psalm-suppress --no-diff --no-cache --no-file-cache

    unit-tests:
        runs-on: ubuntu-latest
        if: ${{ !contains(github.event.head_commit.message, 'skip tests') }}
        env:
            USE_COVERAGE: no
        strategy:
            fail-fast: false
            matrix:
                php-ver: [ '7.4', '8.0', '8.1', '8.2' ]
                composer-ver: [ '~2.3.0', '~2.4.0', '~2.5.0' ]
                dependency-versions: [ 'highest', 'lowest' ]
        steps:
            -   name: Update "USE_COVERAGE" env var based on matrix
                if: ${{ matrix.php-ver == '7.4' && matrix.composer-ver == '~2.5.0' }}
                run: echo "USE_COVERAGE=yes" >> $GITHUB_ENV

            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-ver }}
                    ini-values: zend.assertions=1, error_reporting=E_ALL, display_errors=On
                    coverage: ${{ ((env.USE_COVERAGE == 'yes') && 'xdebug') || 'none' }}

            -   name: Adjust Composer dependencies
                run:  composer require --dev --no-update "composer/composer:${{ matrix.composer-ver }}"

            -   name: Install dependencies
                uses: ramsey/composer-install@v2
                with:
                    dependency-versions: ${{ matrix.dependency-versions }}

            -   name: Run unit tests
                run: ./vendor/bin/phpunit ${{ ((env.USE_COVERAGE == 'yes') && '--coverage-html=coverage-report') || '--no-coverage' }}

            -   name: Upload coverage report
                uses: actions/upload-artifact@v3
                if: ${{ env.USE_COVERAGE == 'yes' }}
                with:
                    name: coverage-report
                    path: coverage-report/

    lint:
        runs-on: ubuntu-latest
        if: ${{ !contains(github.event.head_commit.message, 'skip lint') }}
        strategy:
            fail-fast: true
            matrix:
                php-ver: [ '7.4', '8.0', '8.1', '8.2' ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-ver }}
                    ini-values: zend.assertions=1, error_reporting=E_ALL, display_errors=On
                    tools: parallel-lint

            -   name: Check syntax error in sources
                run: parallel-lint ./src/
